repository: authorlwf/authorlwf.github.io
repository_url: https://github.com/authorlwf

timezone: Asia/Shanghai
lang: zh_CN

title1: 立方体 · authorlwf
title: 立方体Cube
alias_en: authorlwf
alias_cn: 絺绤导航
# description: A Navigation Website for BYR
keywords: 絺绤导航, BYR-Navi, BYR, BUPT, Navi, Navigation
url: https://authorlwf.top
established_at: "2022-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net

zhihu_url: https://www.zhihu.com/people/authorlwf
zhihu:   知乎

weixin_url: https://mp.weixin.qq.com/s/VUr0DffMom3VTX30xcvidQ
weixin:   微信公众号

bilibili_url: https://space.bilibili.com/502300068?spm_id_from=333.1007.0.0
bilibili:   哔哩哔哩

cxyhz_url: https://www.coderutil.com/
cxyhz: 程序员盒子



contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

update_interval: 60000

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
